// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Original project — djmrevzcetdpjzbggavj (user's real data: 26 products, orders, accounts)
const SUPABASE_URL = "https://djmrevzcetdpjzbggavj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqbXJldnpjZXRkcGp6YmdnYXZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5OTk5NjIsImV4cCI6MjA5NjU3NTk2Mn0.QxA_F92I9otKySh_eSGdHY-8Nwm9ZqRmgL4nas00ifE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
