// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded to correct project — bypasses any stale Vercel env vars
const SUPABASE_URL = "https://qzhcxtqkdcygzadcttyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_F-g0yqW4X3JygjjF0rmJ2w_r0FRioJy";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});
